"""
CISC 4080 - Lab 0
Python Basics

Please complete all functions below and test them in the __main__ section.

Requirements:
1. Write comments for your functions.
2. Test each function using manually created lists.
3. Also test applicable functions using RandomList().
4. Do not use built-in functions such as sorted() to solve the required problems.
"""

import random
"""
Python comes with many built-in libraries (also called modules) that provide
useful functions we can reuse in our programs.

The "random" library provides functions for generating random values.
To use it, we first import it:

    import random

After importing the library, we can call its functions using:

    random.function_name(...)

For example:

     random.randint(1, 10)

returns a random integer between 1 and 10, including both 1 and 10.


Example:

     x = random.randint(1, 10)
     print(x)

 The output could be:

     3

If you run the program again, the result may be different:

     8

In this lab, we use random.randint() to generate random lists so that you
can test your functions on different inputs instead of testing only one
manually created list.

"""

# Please do not modify this function :)
def RandomList(size=10, lower=0, upper=100):
    """
    Generate and return a list of random integers.

    Parameters:
        size: number of elements in the list
        lower: minimum possible value
        upper: maximum possible value

    Returns:
        A list of random integers.
    """
    return [random.randint(lower, upper) for _ in range(size)]


def BubbleSort(numbers):
    """
    TODO:
        Implement Bubble Sort here, and write whatever comments you find necessary.
    """

    # Your code here




def SortedCheck(numbers):
    """
    TODO:
        Implement the checking logic here, and write whatever comments you find necessary.
    """

    # Your code here




def CheckDuplicate_Sorted(numbers):
    """
    Hint:
        Because the list is sorted, duplicate values will appear next to each other.

    TODO:
        Implement the checking logic here, and write whatever comments you find necessary.
    """

    # Your code here




def CheckDuplicate_Unsorted(numbers):
    """
    TODO:
        Implement the checking logic here, and write whatever comments you find necessary.
    """

    # Your code here

 


def IsPalindrome(text):
    """

    TODO:
        Implement the checking logic here, and write whatever comments you find necessary.
    """

    # Your code here

    pass


# ---------------------------------------------------------------------------
# The following block is the main entry point of this Python program.
#
# Python automatically sets the special variable __name__ to "__main__"
# when this file is executed directly. Therefore, the code inside this block
# will run when you execute:
#
#     python lab0.py
#
# However, this block will NOT automatically run if this file is imported
# into another Python program.
#
# In this lab, use the __main__ block to test each function you implement.
# You should test your functions using multiple inputs, including manually
# created lists and lists generated by RandomList().
# ---------------------------------------------------------------------------

if __name__ == "__main__":

    print("===== CISC 4080 Lab 0 =====")

    # ---------------------------------------------------------
    # Test 1: BubbleSort
    # ---------------------------------------------------------
    print("\n--- Testing BubbleSort ---")

    test_list_1 = [5, 2, 8, 1, 4]

    print("Before sorting:", test_list_1)

    # Uncomment after implementing BubbleSort
    # BubbleSort(test_list_1)

    print("After sorting:", test_list_1)


    # ---------------------------------------------------------
    # Test 2: SortedCheck
    # ---------------------------------------------------------
    print("\n--- Testing SortedCheck ---")

    sorted_list = [1, 2, 3, 4, 5]
    unsorted_list = [1, 3, 2, 5, 4]

    # Uncomment after implementing SortedCheck
    # print(sorted_list, "->", SortedCheck(sorted_list))
    # print(unsorted_list, "->", SortedCheck(unsorted_list))

    # print(sorted_list_with bubblesort, "->", SortedCheck(BubbleSort(unsorted_list)))

    # ---------------------------------------------------------
    # Test 3: CheckDuplicate_Sorted
    # ---------------------------------------------------------
    print("\n--- Testing CheckDuplicate_Sorted ---")

    sorted_with_duplicates = [1, 2, 2, 4, 5]
    sorted_without_duplicates = [1, 2, 3, 4, 5]

    # Uncomment after implementing CheckDuplicate_Sorted
    # print(
    #     sorted_with_duplicates,
    #     "->",
    #     CheckDuplicate_Sorted(sorted_with_duplicates)
    # )
    #
    # print(
    #     sorted_without_duplicates,
    #     "->",
    #     CheckDuplicate_Sorted(sorted_without_duplicates)
    # )


    # ---------------------------------------------------------
    # Test 4: CheckDuplicate_Unsorted
    # ---------------------------------------------------------
    print("\n--- Testing CheckDuplicate_Unsorted ---")

    unsorted_with_duplicates = [5, 2, 8, 2, 1]
    unsorted_without_duplicates = [5, 2, 8, 4, 1]

    # Uncomment after implementing CheckDuplicate_Unsorted
    # print(
    #     unsorted_with_duplicates,
    #     "->",
    #     CheckDuplicate_Unsorted(unsorted_with_duplicates)
    # )
    #
    # print(
    #     unsorted_without_duplicates,
    #     "->",
    #     CheckDuplicate_Unsorted(unsorted_without_duplicates)
    # )


    # ---------------------------------------------------------
    # Test 5: IsPalindrome
    # ---------------------------------------------------------
    print("\n--- Testing IsPalindrome ---")

    # Uncomment after implementing IsPalindrome
    # print("Welcome ->", IsPalindrome("Welcome"))
    # print("kayak ->", IsPalindrome("kayak"))
    # print("level ->", IsPalindrome("level"))
    # print("python ->", IsPalindrome("python"))


    # ---------------------------------------------------------
    # Test using randomly generated lists
    # ---------------------------------------------------------
    print("\n--- Testing with Random Lists ---")

    random_list = RandomList(10, 0, 20)

    print("Random list:", random_list)

    # You may use the random list to test your functions below.

    # Example:
    #
    # BubbleSort(random_list)
    # print("Sorted random list:", random_list)
    # print("SortedCheck:", SortedCheck(random_list))
    # print(
    #     "Contains duplicates:",
    #     CheckDuplicate_Sorted(random_list)
    # )